#!/usr/bin/env bash

set -eu

TIMESTAMP=$(date +%Y-%m-%d)

docker build -t curl-http3:quiche-$TIMESTAMP -f quiche/Dockerfile .
docker build -t curl-http3:ngtcp2-$TIMESTAMP -f ngtcp2/Dockerfile .

docker tag curl-http3:quiche-$TIMESTAMP curl-http3:quiche-latest
docker tag curl-http3:ngtcp2-$TIMESTAMP curl-http3:ngtcp2-latest
