on:
  push:
    branches: "*"
  schedule:
    - cron: "0 0 * * *"
jobs:
  quiche:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/unasuke/curl-http3
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=quiche-
            type=raw,value=quiche-latest
            type=sha,prefix=quiche-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: quiche
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
  ngtcp2:
    runs-on: ubuntu-20.04
    steps:
      - run: date +%Y-%m-%d
        id: date
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/unasuke/curl-http3
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=ngtcp2-
            type=raw,value=ngtcp2-latest
            type=sha,prefix=ngtcp2-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ngtcp2
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
  msh3:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v3
        id: meta
        with:
          images: ghcr.io/unasuke/curl-http3
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=msh3-
            type=raw,value=msh3-latest
            type=sha,prefix=msh3-
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: msh3
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
  build-and-test:
    needs: [quiche, ngtcp2, msh3]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: build and test
        run: |
          ./test

