name: msh3
on:
  push:
    branches: "*"
    paths:
      - "msh3/**"
      - ".github/**"
  schedule:
    - cron: "0 0 * * *"
jobs:
  msh3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/unasuke/curl-http3
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=msh3-
            type=raw,value=msh3-latest
            type=sha,prefix=msh3-
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: msh3
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
  build-and-test:
    needs: [msh3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: build and test
        run: |
          ./tests/msh3.bash
