name: ngtcp2
on:
  push:
    branches: "*"
    paths:
      - "ngtcp2/**"
      - ".github/**"
  schedule:
    - cron: "0 0 * * *"
jobs:
  ngtcp2:
    runs-on: ubuntu-latest
    steps:
      - run: date +%Y-%m-%d
        id: date
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/unasuke/curl-http3
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=ngtcp2-
            type=raw,value=ngtcp2-latest
            type=sha,prefix=ngtcp2-
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ngtcp2
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
  build-and-test:
    needs: [ngtcp2]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: build and test
        run: |
          ./tests/ngtcp2.bash
