name: quiche
on:
  push:
    branches: "*"
    paths:
      - "quiche/**"
      - ".github/**"
  schedule:
    - cron: "0 0 * * *"
jobs:
  quiche:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/unasuke/curl-http3
          tags: |
            type=schedule,pattern={{date 'YYYY-MM-DD'}},prefix=quiche-
            type=raw,value=quiche-latest
            type=sha,prefix=quiche-
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: quiche
          push: true
          no-cache: true
          tags: ${{ steps.meta.outputs.tags }}
  build-and-test:
    needs: [quiche]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: docker/setup-buildx-action@v3
      - name: build and test
        run: |
          ./tests/quiche.bash
